### ISSUE TITLE
Problem with configuration in variable.tf

### ISSUE THREAD

**Issue by mahendra-mehra** [oracle-devrel/terraform-oci-arch-ci-cd-devops#13]
terraform init throws this error
![variable-tf](https://user-images.githubusercontent.com/14244915/182792096-b51d5c91-51a7-4863-a75d-ac721a9d4de8.png)

It was solved when I commented the second default argument.
variable "release" {
  description = "Reference Architecture Release (OCI Architecture Center)"
  default     = "1.1.0"
#default     = "1.0.6"

 Let me know if this is the correct approach.

**Comment by mp3monster** [comment]
Nice spot.  Your fix is correct and we've just submitted a patch fix for this.
