### ISSUE TITLE
Error: 409-Conflict, Kubernetes version does not match Kubernetes version of OKE worker node image (v1.23.4) 

### ISSUE THREAD

**Issue by mahendra-mehra** [oracle-devrel/terraform-oci-arch-ci-cd-devops#14]
Getting this error during terraform apply operation

Error: 409-Conflict, Kubernetes version does not match Kubernetes version of OKE worker node image (v1.23.4) 
│ Suggestion: The resource is in a conflicted state. Please retry again or contact support for help with service: Containerengine Node Pool
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_node_pool 
│ API Reference: https://docs.oracle.com/iaas/api/#/en/containerengine/20180222/NodePool/CreateNodePool 
│ Request Target: POST https://containerengine.us-phoenix-1.oci.oraclecloud.com/20180222/nodePools 
│ Provider version: 4.87.0, released on 2022-08-03.  
│ Service: Containerengine Node Pool 
│ Operation Name: CreateNodePool 
│ OPC request ID: f68edbeb2a78c6f17cce5288637d37f1/18C45FCF00B120A15F90849C957158A3/79CC752ED67FC51A3571316D8C0978E9 
│ 
│ 
│   with module.oci-oke[0].oci_containerengine_node_pool.oci_oke_node_pool,
│   on .terraform/modules/oci-oke/oke.tf line 53, in resource "oci_containerengine_node_pool" "oci_oke_node_pool":
│   53: resource "oci_containerengine_node_pool" "oci_oke_node_pool" {

**Comment by mp3monster** [comment]
I think this is a version conflict for OKE. I believe if you remove line 22 in oke.tf the module will adopt a version that will not be a problem.  We're looking into a proper fix.

**Comment by nugoncal** [comment]
Hi @mahendra-mehra,
I've analyzed the issue and found out that this is temporary. There's a new OKE version released 5 days ago - v1.24.1 , but the compatible Oracle Linux image hasn't been released yet. I expect the problem to disappear on its own within a couple of days.
In the meantime, if you wish, you could manually pass the OKE version which is the one before the last, meaning v1.23.4
You can do this by adding the following line to your terraform.tfvars file:
```
k8s_version = "v1.23.4" 
```
Or, in Oracle Resource Manager, you can type the same in the Kubernetes version box. Note that you'll have to tick the "Show advanced options" checkbox at the top, in "Required configuration", for the Kubernetes version input to be visible.
