### ISSUE TITLE
OKE version error v1.23.4 vs v1.24.1

### ISSUE THREAD

**Issue by mikarinneoracle** [oracle-devrel/terraform-oci-arch-ci-cd-devops#17]
Error: 409-Conflict, Kubernetes version does not match Kubernetes version of OKE worker node image (v1.23.4).

**Comment by mikarinneoracle** [comment]
_New OKE cluster_ option was used.

**Comment by mikarinneoracle** [comment]
**From the resource manager stack apply log:**

2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] Error: local-exec provisioner error
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO]   with null_resource.clonerepo,
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO]   on coderepo.tf line 33, in resource "null_resource" "clonerepo":
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO]   33:   provisioner "local-exec" {
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] Error running command 'echo '(3) Starting git clone command... '; echo
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] 'Username: Before' xxxxxxxxxxxx; echo 'Username: After'
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] xxxxxxxxxxxxxxxxxxxxxx git clone
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] https://xxxxxxxxxxxxxxxxxx:%3C-%5DbcK0e6r-PY%3C7SjONS@devops.scmservice.eu-frankfurt-1.oci.oraclecloud.com/namespaces/xxxxxxxxxxxx/projects/devopsproject_1h55/repositories/nodejs;':
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] exit status 128. Output: (3) Starting git clone command... 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] Cloning into 'nodejs'...
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] fatal: Authentication failed for
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] 'https://devops.scmservice.eu-frankfurt-1.oci.oraclecloud.com/namespaces/xxxxxxx/projects/devopsproject_1h55/repositories/nodejs/'
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] Error: 409-Conflict, Kubernetes version does not match Kubernetes version of OKE worker node image (v1.23.4) 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] Suggestion: The resource is in a conflicted state. Please retry again or contact support for help with service: Containerengine Node Pool
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_node_pool 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] API Reference: https://docs.oracle.com/iaas/api/#/en/containerengine/20180222/NodePool/CreateNodePool 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] Request Target: POST https://containerengine.eu-frankfurt-1.oci.oraclecloud.com/20180222/nodePools 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] Provider version: 4.88.1, released on 2022-08-11.  
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] Service: Containerengine Node Pool 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] Operation Name: CreateNodePool 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] OPC request ID: fd860ffdee4db1c232045b08c6a8bf66/DFCBAEE889C332185C30136DEB5A98D7/22A06EDA6340EFDEC4C0396F6B3C92DB 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO]   with module.oci-oke[0].oci_containerengine_node_pool.oci_oke_node_pool,
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO]   on .terraform/modules/oci-oke/oke.tf line 53, in resource "oci_containerengine_node_pool" "oci_oke_node_pool":
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO]   53: resource "oci_containerengine_node_pool" "oci_oke_node_pool" {
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO] 
2022/08/17 06:34:16[TERRAFORM_CONSOLE] [INFO]

**Comment by RahulMR42** [comment]
Thank you for notifying us , We shall update you with the fix soon .

**Comment by RahulMR42** [comment]
Can you retry the stack creation as the default for OKE is fixed - https://github.com/oracle-devrel/terraform-oci-arch-oke/pull/7

**Comment by mikarinneoracle** [comment]
Thanks, we will. Will report back.

**Comment by mikarinneoracle** [comment]
New error:

Invalid index referring to LB_IP.

**Comment by RahulMR42** [comment]
Can you paste the error here please ?

**Comment by mikarinneoracle** [comment]
It is an screen shot, I will send it to you directly.

**Comment by mikarinneoracle** [comment]
Error: Invalid index
  on oke-outputs.tf line 34, in output "LB_IP"
  34:   value = data.oci_load_balancer_load_balancers.LBs.load_balancers[0].ip_addresses
    ├────────────────
    │ data.oci_load_balancer_load_balancers.LBs.load_balancers is empty list of object
The given key does not identify an element in this collection value.

**Comment by mikarinneoracle** [comment]
Sorry, thought it was screenshot but it wasn't :D above. Thanks!

**Comment by RahulMR42** [comment]
Okie , i will make a fix ,someone added a loadbalancer view here ,which is not correct as the loadbalancer will take some time (build + deploy) to get poped up .The error is just on the output side ,so ideally the resources should be created ok

**Comment by mikarinneoracle** [comment]
right, thanks.

**Comment by RahulMR42** [comment]
The new release should fix this, please let us know your feedback.
