### ISSUE TITLE
Terraform error

### ISSUE THREAD

**Issue by mp3monster** [oracle-devrel/terraform-oci-arch-ci-cd-devops#8]
The 1 click deploy process is failing with a Terraform issue.  So executing with Resource Manager.

The log shows :

022/06/14 16:52:11[TERRAFORM_CONSOLE] [INFO] Getting providers hosted on RMS
2022/06/14 16:52:11[TERRAFORM_CONSOLE] [INFO] Initializing modules...
2022/06/14 16:52:11[TERRAFORM_CONSOLE] [INFO] Downloading github.com/oracle-devrel/terraform-oci-arch-oke for oci-oke...
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - oci-oke in .terraform/modules/oci-oke
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] 
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] Initializing provider plugins...
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Finding latest version of oracle/oci...
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Finding latest version of hashicorp/oci...
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Finding latest version of hashicorp/null...
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Finding latest version of hashicorp/tls...
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Finding latest version of hashicorp/random...
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Finding latest version of hashicorp/local...
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Installing oracle/oci v4.79.0...
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Installed oracle/oci v4.79.0 (unauthenticated)
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Installing hashicorp/oci v4.79.0...
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Installed hashicorp/oci v4.79.0 (unauthenticated)
2022/06/14 16:52:12[TERRAFORM_CONSOLE] [INFO] - Installing hashicorp/null v3.1.0...
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] - Installed hashicorp/null v3.1.0 (unauthenticated)
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] - Installing hashicorp/tls v3.1.0...
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] - Installed hashicorp/tls v3.1.0 (unauthenticated)
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] - Installing hashicorp/random v3.1.0...
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] - Installed hashicorp/random v3.1.0 (unauthenticated)
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] - Installing hashicorp/local v2.1.0...
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] - Installed hashicorp/local v2.1.0 (unauthenticated)
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] 
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] Terraform has created a lock file .terraform.lock.hcl to record the provider
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] selections it made above. Include this file in your version control repository
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] so that Terraform can guarantee to make the same selections by default when
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] you run "terraform init" in the future.
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] 
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] Terraform has been successfully initialized!
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] 
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] You may now begin working with Terraform. Try running "terraform plan" to see
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] any changes that are required for your infrastructure. All Terraform commands
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] should now work.
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] 
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] If you ever set or change modules or backend configuration for Terraform,
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] rerun this command to reinitialize your working directory. If you forget, other
2022/06/14 16:52:13[TERRAFORM_CONSOLE] [INFO] commands will detect it and remind you to do so if necessary.
2022/06/14 16:53:15[TERRAFORM_CONSOLE] [INFO] 
2022/06/14 16:53:15[TERRAFORM_CONSOLE] [INFO] Error: Unsupported argument
2022/06/14 16:53:15[TERRAFORM_CONSOLE] [INFO] 
2022/06/14 16:53:15[TERRAFORM_CONSOLE] [INFO]   on oke.tf line 32, in module "oci-oke":
2022/06/14 16:53:15[TERRAFORM_CONSOLE] [INFO]   32:   availability_domain                                                         = data.oci_identity_availability_domains.ADs.availability_domains[0]["name"]
2022/06/14 16:53:15[TERRAFORM_CONSOLE] [INFO] 
2022/06/14 16:53:15[TERRAFORM_CONSOLE] [INFO] An argument named "availability_domain" is not expected here.
2022/06/14 16:53:15[TERRAFORM_CONSOLE] [INFO]

**Comment by lfeldman** [comment]
@mp3monster we have fixed a few errors and now RMS is capable to deploy the stack with [the latest release](https://github.com/oracle-devrel/terraform-oci-arch-ci-cd-devops/releases/tag/v1.0.6):
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/19390609/173847067-c818dcbe-9ee3-421c-abaa-d40225a95bb4.png">
